using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Microsoft.Band.Admin")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyTrademark("")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: ComVisible(false)]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Desktop")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Store")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Phone")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Uno")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Windows")]
[assembly: InternalsVisibleTo("Microsoft.Health.App.Background")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Phone.Test")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Phone.Manual.Test")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Desktop.Test")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Desktop.Manual.Test")]
[assembly: InternalsVisibleTo("Microsoft.Band.E2E.Admin.Phone.Test")]
[assembly: InternalsVisibleTo("Phone8Test.Stub")]
[assembly: InternalsVisibleTo("KDKStressTest")]
[assembly: InternalsVisibleTo("CargoStressTestRT")]
[assembly: AssemblyFileVersion("1.4.0.0")]
[assembly: AssemblyVersion("1.4.0.0")]
